apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yeaktonghan/devops-simple-spring-cd
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: spring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true